console.time("mycode");
console.log("Hello Console");
console.log(34 + 4);
console.log(true);
console.log([34, 2, 1, 2]);
console.table({ harry: "this", marks: 34 });
console.warn("This is a warning");
console.log({ harry: "Aneeq", age: 234 });
//console.clear();
console.timeEnd("mycode");
console.assert(234 < 189, "This is possible");
console.error("This is an error");
